apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dev-nginx.p7devs.com
      secretName: p7devs-tls  
  rules:
    - host: dev-nginx.p7devs.com
      http:
        paths:
          - path: /nginx
            pathType: Prefix
            backend:
              service:
                name: nginx-app-service
                port:
                  number: 80

          - path: /apache
            pathType: Prefix
            backend:
              service:
                name: apache-app-service
                port:
                  number: 80
