apiVersion: apps/v1
kind: Deployment
metadata:
  name: veggold
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veggold
  template:
    metadata:
      labels:
        app: veggold
    spec:
      containers:
      - name: veggold
        image: krishnamoorthy1/nginx-ci:veg
        ports:
        - containerPort: 8000
        # ---- Probes Added ----
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1

        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3        
        env:
        - name: DB_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: veggold-config
              key: DB_CONNECTION
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: veggold-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: veggold-config
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: veggold-config
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: veggold-db-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: veggold-db-secret
              key: DB_PASSWORD
---



apiVersion: v1
kind: Service
metadata:
  name: veggold-service
  namespace: prod
spec:  
  selector:
    app: veggold
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
