apiVersion: v1
kind: Secret
metadata:
  name: veggold-db-secret
  namespace: prod
type: Opaque
data:
  DB_USERNAME: YWR1c2Vy        # base64 encoded 'aduser'
  DB_PASSWORD: YWR1c2Vy        # base64 encoded 'aduser'
